import UIKit

enum ImageAsset: String, CaseIterable {
    case appleIcon = "apple_icon"
    case arrowNext = "arrow_next"
    case arrowPrev = "arrow_prev"
    case backArrow = "back_arrow"
    case backCircleBig = "back_circle_big"
    case backCircle = "back_circle"
    case backContainer = "back_container"
    case becomeHost = "become_host"
    case buttonChangeProfilePhoto = "button_change_profile_photo"
    case buttonDeleteSmall = "button_delete_small"
    case buttonProfile = "button_profile"
    case checkbox = "checkbox"
    case checkboxSelected = "checkbox_selected"
    case closeSmallGreen = "close_small_green"
    case coinBackground = "coin_background"
    case coinShopping = "coin_shopping"
    case document = "document"
    case doneBig = "done_big"
    case doneBigHost = "done_big_host"
    case googleIcon = "google_icon"
    case guestMan = "guest_man"
    case iconAccount = "icon_account"
    case iconCalendar = "icon_calendar"
    case iconChat = "icon_chat"
    case iconChecklistInterview = "icon_checklist_interview"
    case iconChecklistQuiz = "icon_checklist_quiz"
    case iconCoffeeTime = "icon_coffee_time"
    case iconDinnerTogether = "icon_dinner_together"
    case iconDocument = "icon_document"
    case iconListenMore = "icon_listen_more"
    case iconLunchTogether = "icon_lunch_together"
    case iconMorningCheckIn = "icon_morning_check_in"
    case iconNightTimeCheckIn = "icon_night_time_check_in"
    case iconPaypal = "icon_paypal"
    case iconStudyWithMe = "icon_study_with_me"
    case iconTalkMore = "icon_talk_more"
    case iconVentToMe = "icon_vent_to_me"
    case iconVideo = "icon_video"
    case iconVirtualWalks = "icon_virtual_walks"
    case iconWalletWithMoney = "icon_wallet_with_money"
    case iconWallet = "icon_wallet"
    case iconWorkWithMe = "icon_work_with_me"
    case iconYoga = "icon_yoga"
    case invoiceBackground = "invoice_background"
    case navbarShade = "navbar_shade"
    case paypalBig = "paypal_big"
    case playVideo = "play_video"
    case profileDefault = "profile_default"
    case quizDone = "quiz_done"
    case selectorDivider = "selector_divider"
    case selectorGuest = "selector_guest"
    case selectorHost = "selector_host"
    case separator = "separator"
    case sidebarIconProfile = "sidebar_icon_profile"
    case sidebarIconEmail = "sidebar_icon_email"
    case sidebarIconPhone = "sidebar_icon_phone"
    case sidebarIconPrivacy = "sidebar_icon_privacy"
    case sidebarIconSignOut = "sidebar_icon_sign_out"
    case splashUnderline = "splash_underline"
    case starSmallEmpty = "star_small_empty"
    case starSmallFull = "star_small_full"
    case starSmallHalf = "star_small_half"
    case swipeHandlerActive = "swipe_handler_active"
    case triangleDown = "triangle_down"
    case triangleUp = "triangle_up"
    case venmoBig = "venmo_big"
    case wCoin = "w_coin"
    case wythYouLogoText = "wyth_you_logo_text"
    case wythYouLogo = "wyth_you_logo"
    case youtubeIcon = "youtube_icon"

    var image: UIImage {
        UIImage(named: rawValue)!
    }
}
